// Code generated by Kitex v0.12.2. DO NOT EDIT.

package paymentservice

import (
	"context"
	payment "github.com/bitdance-panic/gobuy/app/rpc/kitex_gen/payment"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreatePayment(ctx context.Context, req *payment.CreatePaymentRequest, callOptions ...callopt.Option) (r *payment.CreatePaymentResponse, err error)
	GetPayment(ctx context.Context, req *payment.GetPaymentRequest, callOptions ...callopt.Option) (r *payment.GetPaymentResponse, err error)
	UpdatePayment(ctx context.Context, req *payment.UpdatePaymentRequest, callOptions ...callopt.Option) (r *payment.UpdatePaymentResponse, err error)
	DeletePayment(ctx context.Context, req *payment.DeletePaymentRequest, callOptions ...callopt.Option) (r *payment.DeletePaymentResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPaymentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPaymentServiceClient struct {
	*kClient
}

func (p *kPaymentServiceClient) CreatePayment(ctx context.Context, req *payment.CreatePaymentRequest, callOptions ...callopt.Option) (r *payment.CreatePaymentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePayment(ctx, req)
}

func (p *kPaymentServiceClient) GetPayment(ctx context.Context, req *payment.GetPaymentRequest, callOptions ...callopt.Option) (r *payment.GetPaymentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPayment(ctx, req)
}

func (p *kPaymentServiceClient) UpdatePayment(ctx context.Context, req *payment.UpdatePaymentRequest, callOptions ...callopt.Option) (r *payment.UpdatePaymentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdatePayment(ctx, req)
}

func (p *kPaymentServiceClient) DeletePayment(ctx context.Context, req *payment.DeletePaymentRequest, callOptions ...callopt.Option) (r *payment.DeletePaymentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeletePayment(ctx, req)
}
