// Code generated by Kitex v0.12.1. DO NOT EDIT.

package orderservice

import (
	"context"
	order "github.com/bitdance-panic/gobuy/app/rpc/kitex_gen/order"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateOrder(ctx context.Context, req *order.CreateOrderRequest, callOptions ...callopt.Option) (r *order.CreateOrderResponse, err error)
	UpdateOrder(ctx context.Context, req *order.UpdateOrderRequest, callOptions ...callopt.Option) (r *order.UpdateOrderResponse, err error)
	GetUserOrders(ctx context.Context, req *order.GetUserOrdersRequest, callOptions ...callopt.Option) (r *order.GetUserOrdersResponse, err error)
	DeleteOrder(ctx context.Context, req *order.DeleteOrderRequest, callOptions ...callopt.Option) (r *order.DeleteOrderResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*kClient
}

func (p *kOrderServiceClient) CreateOrder(ctx context.Context, req *order.CreateOrderRequest, callOptions ...callopt.Option) (r *order.CreateOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrder(ctx, req)
}

func (p *kOrderServiceClient) UpdateOrder(ctx context.Context, req *order.UpdateOrderRequest, callOptions ...callopt.Option) (r *order.UpdateOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOrder(ctx, req)
}

func (p *kOrderServiceClient) GetUserOrders(ctx context.Context, req *order.GetUserOrdersRequest, callOptions ...callopt.Option) (r *order.GetUserOrdersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserOrders(ctx, req)
}

func (p *kOrderServiceClient) DeleteOrder(ctx context.Context, req *order.DeleteOrderRequest, callOptions ...callopt.Option) (r *order.DeleteOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteOrder(ctx, req)
}
