// Code generated by Kitex v0.12.2. DO NOT EDIT.

package cartservice

import (
	"context"
	cart "github.com/bitdance-panic/gobuy/app/rpc/kitex_gen/cart"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateItem(ctx context.Context, req *cart.CreateItemReq, callOptions ...callopt.Option) (r *cart.CreateItemResp, err error)
	UpdateQuantity(ctx context.Context, req *cart.UpdateQuantityReq, callOptions ...callopt.Option) (r *cart.UpdateQuantityResp, err error)
	DeleteItem(ctx context.Context, req *cart.DeleteItemReq, callOptions ...callopt.Option) (r *cart.DeleteItemResp, err error)
	GetItem(ctx context.Context, req *cart.GetItemReq, callOptions ...callopt.Option) (r *cart.GetItemResp, err error)
	ListItem(ctx context.Context, req *cart.ListItemReq, callOptions ...callopt.Option) (r *cart.ListItemResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCartServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCartServiceClient struct {
	*kClient
}

func (p *kCartServiceClient) CreateItem(ctx context.Context, req *cart.CreateItemReq, callOptions ...callopt.Option) (r *cart.CreateItemResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateItem(ctx, req)
}

func (p *kCartServiceClient) UpdateQuantity(ctx context.Context, req *cart.UpdateQuantityReq, callOptions ...callopt.Option) (r *cart.UpdateQuantityResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateQuantity(ctx, req)
}

func (p *kCartServiceClient) DeleteItem(ctx context.Context, req *cart.DeleteItemReq, callOptions ...callopt.Option) (r *cart.DeleteItemResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteItem(ctx, req)
}

func (p *kCartServiceClient) GetItem(ctx context.Context, req *cart.GetItemReq, callOptions ...callopt.Option) (r *cart.GetItemResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItem(ctx, req)
}

func (p *kCartServiceClient) ListItem(ctx context.Context, req *cart.ListItemReq, callOptions ...callopt.Option) (r *cart.ListItemResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListItem(ctx, req)
}
