name: Pull Request Check

on: [pull_request]

jobs:
  prcheck:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go Mod Tidy
        run: ./scripts/tidy.sh

      - name: Run Go Tests
        run: ./scripts/test.sh

      # 缓存 gofumpt
      - name: Cache gofumpt binary
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/gofumpt
          key: ${{ runner.os }}-gofumpt-${{ hashFiles('go.mod', 'go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gofumpt-

      - name: Install gofumpt
        if: steps.cache-gofumpt.outputs.cache-hit != 'true'
        run: |
          go install mvdan.cc/gofumpt@latest

      # 缓存 golangci-lint
      - name: Cache golangci-lint binary
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ hashFiles('go.mod', 'go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golangci-lint-

      - name: Install golangci-lint
        if: steps.cache-golangci-lint.outputs.cache-hit != 'true'
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.63.4

      - name: Run Go Lint
        run: ./scripts/lint.sh

      # 缓存 gosec
      - name: Cache gosec binary
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/gosec
          key: ${{ runner.os }}-gosec-${{ hashFiles('go.mod', 'go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gosec-

      - name: Install gosec
        if: steps.cache-gosec.outputs.cache-hit != 'true'
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Check for vulnerabilities with GoSec
        run: gosec ./...
